name: 'your_app'
version: 0.0.0
description: Your App description.
author: Your Name <your-name@example.com>
homepage:

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  browser: ^0.10.0+2
  polymer_elements: ^1.0.0-rc.5
  polymer: ^1.0.0-rc.9
  reflectable: ^0.4.0
  web_components: ^0.12.0+4
  route_hierarchical: any

transformers:
- web_components:
    entry_points: web/index.html
- reflectable:
    entry_points: web/index.bootstrap.initialize.dart
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
