name: 'your_app'
version: 0.0.0
description: Your App description.
author: Your Name <your-name@example.com>
homepage:

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  browser: ^0.10.0
  web_components: ^0.12.0
  polymer: ^1.0.0-rc.13
  polymer_elements: ^1.0.0-rc.7
  route_hierarchical: any

transformers:
- polymer:
    entry_points: web/index.html
- $dart2js:
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
